import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams } from 'expo-router';
import { Clock } from 'lucide-react-native';
import Header from '../../components/Header';
import { useTheme } from '../../lib/theme';
import { useTranslation } from '../../lib/i18n';

// Dummy article content per slug
const CONTENT: Record<string, { title: string; readTime: string; sections: { heading: string; body: string }[] }> = {
  'credit-score': {
    title: 'Understanding Your CIBIL Score',
    readTime: '5 min read',
    sections: [
      {
        heading: 'What is a CIBIL Score?',
        body: 'A CIBIL score (also called a credit score) is a 3-digit number ranging from 300 to 900. It is generated by TransUnion CIBIL, one of India\'s four credit bureaus. Lenders use this score to assess your creditworthiness before approving a loan or credit card.\n\nA score above 750 is considered excellent and significantly improves your chances of loan approval at better interest rates.',
      },
      {
        heading: 'How is it Calculated?',
        body: '• Payment History (35%) — Timely repayment of EMIs and credit card bills\n• Credit Utilization (30%) — How much of your available credit limit you use\n• Credit Age (15%) — Length of your credit history\n• Credit Mix (10%) — Variety of credit types (loans, cards)\n• New Inquiries (10%) — Number of recent loan applications',
      },
      {
        heading: 'Tips to Improve Your Score',
        body: '1. Always pay EMIs and credit card bills before the due date\n2. Keep credit card utilization below 30%\n3. Avoid applying for multiple loans simultaneously\n4. Maintain a healthy mix of secured and unsecured credit\n5. Regularly check your credit report for errors and dispute incorrect entries',
      },
      {
        heading: 'Why it Matters for Udofin',
        body: 'When you apply through Udofin, we perform a soft credit pull (which does NOT impact your score) to match you with appropriate lenders. A higher score unlocks better rates and higher loan amounts from our partner banks.',
      },
    ],
  },
  'loan-guides': {
    title: 'Complete Loan Application Guide',
    readTime: '8 min read',
    sections: [
      {
        heading: 'Before You Apply',
        body: 'Check your credit score, gather income documents, and calculate your EMI affordability using Udofin\'s EMI Calculator. Determine the loan type that best suits your need — personal, home, vehicle, or gold loan.',
      },
      {
        heading: 'Step-by-Step: Applying via Udofin',
        body: '1. Select your loan type and desired amount\n2. Enter employment and income details\n3. Provide your residential address\n4. Review the summary and consent to bureau check\n5. Compare matched lender offers\n6. Review the Key Fact Statement (KFS)\n7. Digitally sign the loan agreement\n8. Loan disbursed within 24–48 hours',
      },
      {
        heading: 'Documents Required',
        body: '• PAN Card (mandatory)\n• Aadhaar Card\n• Last 3 months salary slips\n• 6-month bank statement\n• Latest ITR (for self-employed)\n• Proof of address',
      },
      {
        heading: 'RBI-Mandated Disclosures',
        body: 'All lenders on Udofin are RBI-registered NBFCs or banks. You will receive a KFS (Key Fact Statement) before signing, disclosing total cost, APR, and all charges — as mandated by RBI\'s Digital Lending Guidelines 2022.',
      },
    ],
  },
  'financial-planning': {
    title: 'Financial Planning Basics',
    readTime: '6 min read',
    sections: [
      {
        heading: 'The 50-30-20 Rule',
        body: 'A simple budgeting framework: allocate 50% of net income to needs (rent, groceries, EMIs), 30% to wants (dining, entertainment), and 20% to savings and investments.',
      },
      {
        heading: 'Emergency Fund First',
        body: 'Before taking on any new loan, build an emergency fund of at least 3–6 months of expenses. This prevents you from defaulting on EMIs during unexpected events like job loss or medical emergencies.',
      },
      {
        heading: 'Debt Management',
        body: 'Use the avalanche method: pay off high-interest debts first (typically credit cards at 36–42% per annum) while maintaining minimum payments on others. This saves the most money in interest over time.',
      },
      {
        heading: 'Responsible Borrowing',
        body: 'Never borrow more than you can comfortably repay. Your total EMI obligations should ideally not exceed 40% of your net monthly income. Use Udofin\'s Eligibility Calculator to find your safe borrowing limit.',
      },
    ],
  },
  'rbi-updates': {
    title: 'Key RBI Updates for Borrowers',
    readTime: '4 min read',
    sections: [
      {
        heading: 'Digital Lending Guidelines 2022',
        body: 'The RBI mandated that all digital lenders must disburse and repay loans directly into the borrower\'s bank account — no third-party pooling. A Key Fact Statement (KFS) with APR must be given before loan execution.',
      },
      {
        heading: 'Right to Prepay',
        body: 'Borrowers of floating-rate loans from banks have the right to prepay without penalty charges. For fixed-rate loans, lenders may charge a prepayment fee — this must be disclosed in the KFS.',
      },
      {
        heading: 'Grievance Redressal',
        body: 'Every RBI-regulated lender must have a Grievance Redressal Officer (GRO). If unresolved within 30 days, you can escalate to the RBI\'s Sachet portal or Banking Ombudsman.',
      },
      {
        heading: 'Fair Practices Code',
        body: 'Lenders cannot use abusive recovery tactics. You have the right to a clear loan repayment schedule, pre-sanction disclosures, and a 3-day cooling-off period to cancel a digital loan without penalty.',
      },
    ],
  },
  'blog': {
    title: 'Udofin Blog',
    readTime: 'Various',
    sections: [
      {
        heading: 'Why Most Loan Applications Get Rejected',
        body: 'Low CIBIL score (below 650), high FOIR, incomplete documentation, and frequent loan applications are the top reasons for rejection. Udofin pre-matches you only with lenders whose criteria you meet.',
      },
      {
        heading: '5 Mistakes to Avoid When Taking a Personal Loan',
        body: '1. Borrowing more than needed\n2. Ignoring the APR (focus on total cost, not just EMI)\n3. Skipping the KFS review\n4. Missing the first EMI date\n5. Not checking prepayment terms',
      },
      {
        heading: 'Gold Loan vs Personal Loan: Which is Better?',
        body: 'Gold loans offer lower interest rates (8–14%) and faster disbursement since gold is collateral. Personal loans have no collateral risk but higher rates (11–24%). Gold loans suit short-term needs; personal loans work for longer tenures.',
      },
    ],
  },
};

export default function LearnArticleScreen() {
  const { slug } = useLocalSearchParams<{ slug: string }>();
  const { colors } = useTheme();
  const styles = getStyles(colors);
  const { t } = useTranslation();

  const article = CONTENT[slug ?? ''] ?? {
    title: 'Article Not Found',
    readTime: '',
    sections: [{ heading: '', body: 'This article is not available yet. Check back soon.' }],
  };

  return (
    <SafeAreaView style={styles.safeArea}>
      <Header title={t('Learn')} />
      <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>

        <Text style={styles.articleTitle}>{t(article.title)}</Text>

        <View style={styles.metaRow}>
          <Clock color={colors.textMuted} size={14} />
          <Text style={styles.metaText}>{article.readTime}</Text>
          <View style={styles.metaDot} />
          <Text style={styles.metaText}>{t('Udofin Editorial')}</Text>
        </View>

        <View style={styles.divider} />

        {article.sections.map((section, i) => (
          <View key={i} style={styles.section}>
            {section.heading ? (
              <Text style={styles.sectionHeading}>{t(section.heading)}</Text>
            ) : null}
            <Text style={styles.sectionBody}>{t(section.body)}</Text>
          </View>
        ))}

        <View style={styles.footerBox}>
          <Text style={styles.footerText}>
            {t('Content for educational purposes only. Not financial advice. Consult a certified financial advisor for personal decisions.')}
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const getStyles = (colors: any) => StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  scroll: { padding: 20, paddingBottom: 40 },
  articleTitle: { fontSize: 24, fontWeight: '900', color: colors.text, lineHeight: 32, marginBottom: 12 },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 16 },
  metaText: { fontSize: 12, color: colors.textMuted, fontWeight: '600' },
  metaDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: colors.textMuted },
  divider: { height: 1, backgroundColor: colors.divider, marginBottom: 24 },
  section: { marginBottom: 24 },
  sectionHeading: {
    fontSize: 16, fontWeight: '800', color: colors.text, marginBottom: 10, lineHeight: 22,
  },
  sectionBody: {
    fontSize: 14, color: colors.textSecondary, lineHeight: 22, fontWeight: '500',
  },
  footerBox: {
    backgroundColor: colors.surface, borderRadius: 14, padding: 16,
    borderWidth: 1, borderColor: colors.surfaceBorder, marginTop: 8,
  },
  footerText: { fontSize: 11, color: colors.textMuted, lineHeight: 16, textAlign: 'center', fontWeight: '500' },
});
